import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Lang = 'es' | 'en' | 'de' | 'ko';

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  es: {
    // Nav
    'nav.home':       'Inicio',
    'nav.catalog':    'Catálogo',
    'nav.admin':      'Admin',
    // Ticker
    'ticker.label':   'MERCADO CAFÉ',
    // Lote fields
    'lote.origin':    'Origen',
    'lote.variety':   'Variedad',
    'lote.process':   'Proceso',
    'lote.altitude':  'Altitud',
    'lote.score':     'Puntuación SCA',
    'lote.weight':    'Disponible',
    'lote.offer':     'Hacer Oferta',
    'lote.sample':    'Solicitar Muestra',
    // Catalog
    'cat.title':      'Catálogo B2B',
    'cat.filter':     'Filtros',
    'cat.search':     'Buscar por nombre, variedad...',
    'cat.loading':    'Cargando lotes...',
    'cat.available':  'lotes disponibles · Precios actualizados',
    'cat.variety':    'Variedad',
    'cat.process':    'Proceso',
    'cat.sca_min':    'SCA Mínimo',
    'cat.municipio':  'Municipio',
    'cat.empty':      'No se encontraron lotes',
    'cat.empty_sub':  'Ajusta tus filtros o búsqueda',
    'cat.clear':      'Limpiar filtros',
    'cat.available_label': 'DISPONIBLE',
    'cat.offered_label':   'OFERTADO',
    'cat.sold_label':      'VENDIDO',
    'cat.draft_label':     'BORRADOR',
    'cat.archived_label':  'ARCHIVADO',
    // Coffee Matcher
    'matcher.title':       'Coffee Matcher',
    'matcher.sub':         'Encuentra tu lote ideal en 4 preguntas',
    'matcher.collapsed':   'Coffee Matcher — Encuentra tu lote ideal',
    'matcher.vol':         '¿Qué cantidad necesitas?',
    'matcher.taste':       'Selecciona uno o más',
    'matcher.sca':         'Puntaje SCA mínimo:',
    'matcher.budget':      'Presupuesto máximo:',
    'matcher.next':        'Siguiente',
    'matcher.results':     'Ver resultados',
    'matcher.prev':        '← Anterior',
    'matcher.vol_sample':  'Muestra (200g gratis)',
    'matcher.vol_micro':   'Microlote (1–10 sacos)',
    'matcher.vol_lot':     'Lote completo (10–50 sacos)',
    'matcher.vol_cont':    'Contenedor (300+ sacos)',
    'matcher.taste_choc':  'Clásico achocolatado',
    'matcher.taste_cit':   'Cítrico y brillante',
    'matcher.taste_flor':  'Floral y delicado',
    'matcher.taste_exo':   'Exótico fermentado',
    'matcher.taste_swe':   'Dulce y miel',
    // Home
    'home.hero':       'El café más trazado del mundo nace aquí',
    'home.sub':        'Comercialización directa de café gourmet del Huila. Precios en tiempo real, trazabilidad blockchain y acceso a los mejores lotes de especialidad.',
    'home.cta':        'Explorar el Catálogo',
    'home.cta2':       '¿Eres caficultor? Únete',
    'home.feat1_t':    'Origen verificado',
    'home.feat1_d':    'Cada lote trazado en blockchain desde la finca hasta tu tostadora. Registro inmutable en Polygon.',
    'home.feat2_t':    'Precio justo en tiempo real',
    'home.feat2_d':    'Precios calculados con datos del mercado NY ICE + diferenciales regionales + prima de calidad SCA.',
    'home.feat3_t':    'Del caficultor al tostador',
    'home.feat3_d':    'Sin intermediarios. Compra directa de productores del Huila con pagos justos y transparentes.',
    'home.featured':   'Lotes Destacados',
    'home.now':        'Disponibles ahora',
    'home.see_all':    'Ver catálogo completo',
    'home.how':        '¿Cómo funciona?',
    'home.how_sub':    'De la finca a tu bodega en 5 pasos simples',
    'home.step1_t':    'Registro',
    'home.step1_d':    'Crea tu cuenta como comprador internacional',
    'home.step2_t':    'Explora',
    'home.step2_d':    'Navega lotes con filtros avanzados y Coffee Matcher',
    'home.step3_t':    'Analiza',
    'home.step3_d':    'Revisa perfiles sensoriales, SCA y trazabilidad blockchain',
    'home.step4_t':    'Oferta',
    'home.step4_d':    'Envía tu oferta formal con precio e incoterm deseados',
    'home.step5_t':    'Recibe',
    'home.step5_d':    'Logística coordinada. De la finca a tu tostadora',
    'home.stat1':      'Caficultores activos',
    'home.stat2':      'Países compradores',
    'home.stat3':      'Puntos SCA máximo',
    'home.stat4':      'Trazable desde la finca',
    'home.voices':     'Voces del Huila',
    'home.voices_sub': 'Lo que dicen nuestros caficultores',
    'home.cta_title':  'Accede al catálogo exclusivo',
    'home.cta_sub':    'Regístrate como comprador internacional y obtén acceso a lotes de especialidad con precios en tiempo real y trazabilidad completa.',
    'home.reg_name':   'Nombre completo',
    'home.reg_co':     'Empresa',
    'home.reg_email':  'Email profesional',
    'home.reg_country':'País',
    'home.reg_btn':    'Quiero acceder al catálogo',
    'home.reg_ok_t':   '¡Solicitud enviada!',
    'home.reg_ok_d':   'Te contactaremos en menos de 24 horas con acceso al catálogo.',
    'home.muestra':    'Muestra',
    'home.oferta':     'Oferta',
    // Footer
    'footer.rights':   '© 2026 Organicode. Todos los derechos reservados.',
    'footer.loc':      'Pitalito, Huila, Colombia',
    'footer.prices':   'Precios en tiempo real',
    'footer.export':   'Exportación internacional',
  },

  en: {
    'nav.home':       'Home',
    'nav.catalog':    'Catalog',
    'nav.admin':      'Admin',
    'ticker.label':   'COFFEE MARKET',
    'lote.origin':    'Origin',
    'lote.variety':   'Variety',
    'lote.process':   'Process',
    'lote.altitude':  'Altitude',
    'lote.score':     'SCA Score',
    'lote.weight':    'Available',
    'lote.offer':     'Make Offer',
    'lote.sample':    'Request Sample',
    'cat.title':      'B2B Catalog',
    'cat.filter':     'Filters',
    'cat.search':     'Search by name, variety...',
    'cat.loading':    'Loading lots...',
    'cat.available':  'lots available · Prices updated',
    'cat.variety':    'Variety',
    'cat.process':    'Process',
    'cat.sca_min':    'Min SCA',
    'cat.municipio':  'Municipality',
    'cat.empty':      'No lots found',
    'cat.empty_sub':  'Adjust your filters or search',
    'cat.clear':      'Clear filters',
    'cat.available_label': 'AVAILABLE',
    'cat.offered_label':   'OFFERED',
    'cat.sold_label':      'SOLD',
    'cat.draft_label':     'DRAFT',
    'cat.archived_label':  'ARCHIVED',
    'matcher.title':       'Coffee Matcher',
    'matcher.sub':         'Find your ideal lot in 4 questions',
    'matcher.collapsed':   'Coffee Matcher — Find your ideal lot',
    'matcher.vol':         'How much do you need?',
    'matcher.taste':       'Select one or more',
    'matcher.sca':         'Minimum SCA score:',
    'matcher.budget':      'Maximum budget:',
    'matcher.next':        'Next',
    'matcher.results':     'See results',
    'matcher.prev':        '← Back',
    'matcher.vol_sample':  'Sample (200g free)',
    'matcher.vol_micro':   'Microlot (1–10 bags)',
    'matcher.vol_lot':     'Full lot (10–50 bags)',
    'matcher.vol_cont':    'Container (300+ bags)',
    'matcher.taste_choc':  'Classic chocolate',
    'matcher.taste_cit':   'Citric & bright',
    'matcher.taste_flor':  'Floral & delicate',
    'matcher.taste_exo':   'Exotic fermented',
    'matcher.taste_swe':   'Sweet & honey',
    'home.hero':       'The world\'s most traceable coffee is born here',
    'home.sub':        'Direct commercialization of gourmet coffee from Huila. Real-time prices, blockchain traceability and access to the finest specialty lots.',
    'home.cta':        'Explore the Catalog',
    'home.cta2':       'Are you a grower? Join us',
    'home.feat1_t':    'Verified origin',
    'home.feat1_d':    'Every lot traced on blockchain from farm to roastery. Immutable record on Polygon.',
    'home.feat2_t':    'Fair price in real time',
    'home.feat2_d':    'Prices calculated with NY ICE market data + regional differentials + SCA quality premium.',
    'home.feat3_t':    'From grower to roaster',
    'home.feat3_d':    'No middlemen. Direct purchase from Huila producers with fair and transparent payments.',
    'home.featured':   'Featured Lots',
    'home.now':        'Available now',
    'home.see_all':    'View full catalog',
    'home.how':        'How does it work?',
    'home.how_sub':    'From the farm to your warehouse in 5 simple steps',
    'home.step1_t':    'Register',
    'home.step1_d':    'Create your account as an international buyer',
    'home.step2_t':    'Explore',
    'home.step2_d':    'Browse lots with advanced filters and Coffee Matcher',
    'home.step3_t':    'Analyze',
    'home.step3_d':    'Review sensory profiles, SCA scores and blockchain traceability',
    'home.step4_t':    'Offer',
    'home.step4_d':    'Submit your formal offer with your desired price and incoterm',
    'home.step5_t':    'Receive',
    'home.step5_d':    'Coordinated logistics. From farm to your roastery',
    'home.stat1':      'Active growers',
    'home.stat2':      'Buyer countries',
    'home.stat3':      'Max SCA score',
    'home.stat4':      'Traceable from farm',
    'home.voices':     'Voices from Huila',
    'home.voices_sub': 'What our growers say',
    'home.cta_title':  'Access the exclusive catalog',
    'home.cta_sub':    'Register as an international buyer and get access to specialty lots with real-time prices and full traceability.',
    'home.reg_name':   'Full name',
    'home.reg_co':     'Company',
    'home.reg_email':  'Business email',
    'home.reg_country':'Country',
    'home.reg_btn':    'I want access to the catalog',
    'home.reg_ok_t':   'Request sent!',
    'home.reg_ok_d':   'We will contact you within 24 hours with catalog access.',
    'home.muestra':    'Sample',
    'home.oferta':     'Offer',
    'footer.rights':   '© 2026 Organicode. All rights reserved.',
    'footer.loc':      'Pitalito, Huila, Colombia',
    'footer.prices':   'Real-time prices',
    'footer.export':   'International export',
  },

  de: {
    'nav.home':       'Startseite',
    'nav.catalog':    'Katalog',
    'nav.admin':      'Admin',
    'ticker.label':   'KAFFEEMARKT',
    'lote.origin':    'Herkunft',
    'lote.variety':   'Sorte',
    'lote.process':   'Aufbereitung',
    'lote.altitude':  'Höhe',
    'lote.score':     'SCA-Bewertung',
    'lote.weight':    'Verfügbar',
    'lote.offer':     'Angebot machen',
    'lote.sample':    'Muster anfordern',
    'cat.title':      'B2B-Katalog',
    'cat.filter':     'Filter',
    'cat.search':     'Nach Name, Sorte suchen...',
    'cat.loading':    'Lose werden geladen...',
    'cat.available':  'Lose verfügbar · Preise aktualisiert',
    'cat.variety':    'Sorte',
    'cat.process':    'Aufbereitung',
    'cat.sca_min':    'SCA Minimum',
    'cat.municipio':  'Gemeinde',
    'cat.empty':      'Keine Lose gefunden',
    'cat.empty_sub':  'Filter oder Suche anpassen',
    'cat.clear':      'Filter löschen',
    'cat.available_label': 'VERFÜGBAR',
    'cat.offered_label':   'ANGEBOTEN',
    'cat.sold_label':      'VERKAUFT',
    'cat.draft_label':     'ENTWURF',
    'cat.archived_label':  'ARCHIVIERT',
    'matcher.title':       'Kaffee-Matcher',
    'matcher.sub':         'Finden Sie Ihr ideales Los in 4 Fragen',
    'matcher.collapsed':   'Kaffee-Matcher — Finden Sie Ihr ideales Los',
    'matcher.vol':         'Wie viel benötigen Sie?',
    'matcher.taste':       'Eines oder mehrere auswählen',
    'matcher.sca':         'Mindest-SCA-Bewertung:',
    'matcher.budget':      'Höchstbudget:',
    'matcher.next':        'Weiter',
    'matcher.results':     'Ergebnisse anzeigen',
    'matcher.prev':        '← Zurück',
    'matcher.vol_sample':  'Muster (200g kostenlos)',
    'matcher.vol_micro':   'Mikro-Los (1–10 Säcke)',
    'matcher.vol_lot':     'Volles Los (10–50 Säcke)',
    'matcher.vol_cont':    'Container (300+ Säcke)',
    'matcher.taste_choc':  'Klassische Schokolade',
    'matcher.taste_cit':   'Zitrus & lebendig',
    'matcher.taste_flor':  'Blumig & zart',
    'matcher.taste_exo':   'Exotisch fermentiert',
    'matcher.taste_swe':   'Süß & Honig',
    'home.hero':       'Der rückverfolgbarste Kaffee der Welt entsteht hier',
    'home.sub':        'Direkter Handel mit Gourmet-Kaffee aus Huila. Echtzeitpreise, Blockchain-Rückverfolgbarkeit und Zugang zu den besten Spezialitätenlosen.',
    'home.cta':        'Katalog erkunden',
    'home.cta2':       'Sind Sie Anbauer? Mitmachen',
    'home.feat1_t':    'Verifizierter Ursprung',
    'home.feat1_d':    'Jedes Los auf der Blockchain vom Hof bis zur Rösterei verfolgt. Unveränderlicher Eintrag auf Polygon.',
    'home.feat2_t':    'Fairer Preis in Echtzeit',
    'home.feat2_d':    'Preise berechnet mit NY ICE Marktdaten + regionalen Differenzialen + SCA-Qualitätsprämie.',
    'home.feat3_t':    'Vom Anbauer zur Rösterei',
    'home.feat3_d':    'Keine Zwischenhändler. Direktkauf von Huila-Produzenten mit fairen, transparenten Zahlungen.',
    'home.featured':   'Ausgewählte Lose',
    'home.now':        'Jetzt verfügbar',
    'home.see_all':    'Vollständigen Katalog anzeigen',
    'home.how':        'Wie funktioniert es?',
    'home.how_sub':    'Von der Farm bis zu Ihrem Lager in 5 einfachen Schritten',
    'home.step1_t':    'Registrieren',
    'home.step1_d':    'Konto als internationaler Käufer erstellen',
    'home.step2_t':    'Erkunden',
    'home.step2_d':    'Lose mit erweiterten Filtern und Coffee Matcher durchsuchen',
    'home.step3_t':    'Analysieren',
    'home.step3_d':    'Geschmacksprofile, SCA-Werte und Blockchain-Rückverfolgbarkeit prüfen',
    'home.step4_t':    'Angebot',
    'home.step4_d':    'Formelles Angebot mit gewünschtem Preis und Incoterm senden',
    'home.step5_t':    'Empfangen',
    'home.step5_d':    'Koordinierte Logistik. Von der Farm zu Ihrer Rösterei',
    'home.stat1':      'Aktive Anbauer',
    'home.stat2':      'Käuferländer',
    'home.stat3':      'Max. SCA-Punkte',
    'home.stat4':      'Von der Farm rückverfolgbar',
    'home.voices':     'Stimmen aus Huila',
    'home.voices_sub': 'Was unsere Anbauer sagen',
    'home.cta_title':  'Zugang zum exklusiven Katalog',
    'home.cta_sub':    'Registrieren Sie sich als internationaler Käufer und erhalten Sie Zugang zu Spezialitätenlosen mit Echtzeitpreisen und vollständiger Rückverfolgbarkeit.',
    'home.reg_name':   'Vollständiger Name',
    'home.reg_co':     'Unternehmen',
    'home.reg_email':  'Geschäfts-E-Mail',
    'home.reg_country':'Land',
    'home.reg_btn':    'Ich möchte Zugang zum Katalog',
    'home.reg_ok_t':   'Anfrage gesendet!',
    'home.reg_ok_d':   'Wir kontaktieren Sie innerhalb von 24 Stunden mit Katalogzugang.',
    'home.muestra':    'Muster',
    'home.oferta':     'Angebot',
    'footer.rights':   '© 2026 Organicode. Alle Rechte vorbehalten.',
    'footer.loc':      'Pitalito, Huila, Kolumbien',
    'footer.prices':   'Echtzeitpreise',
    'footer.export':   'Internationaler Export',
  },

  ko: {
    'nav.home':       '홈',
    'nav.catalog':    '카탈로그',
    'nav.admin':      '관리자',
    'ticker.label':   '커피 시장',
    'lote.origin':    '원산지',
    'lote.variety':   '품종',
    'lote.process':   '가공',
    'lote.altitude':  '고도',
    'lote.score':     'SCA 점수',
    'lote.weight':    '재고',
    'lote.offer':     '오퍼 제출',
    'lote.sample':    '샘플 요청',
    'cat.title':      'B2B 카탈로그',
    'cat.filter':     '필터',
    'cat.search':     '이름, 품종으로 검색...',
    'cat.loading':    '로트 불러오는 중...',
    'cat.available':  '로트 가능 · 가격 업데이트됨',
    'cat.variety':    '품종',
    'cat.process':    '가공',
    'cat.sca_min':    '최소 SCA',
    'cat.municipio':  '지역',
    'cat.empty':      '로트를 찾을 수 없습니다',
    'cat.empty_sub':  '필터 또는 검색을 조정하세요',
    'cat.clear':      '필터 초기화',
    'cat.available_label': '가능',
    'cat.offered_label':   '오퍼 중',
    'cat.sold_label':      '판매됨',
    'cat.draft_label':     '초안',
    'cat.archived_label':  '보관됨',
    'matcher.title':       '커피 매처',
    'matcher.sub':         '4가지 질문으로 이상적인 로트 찾기',
    'matcher.collapsed':   '커피 매처 — 이상적인 로트 찾기',
    'matcher.vol':         '얼마나 필요하신가요?',
    'matcher.taste':       '하나 이상 선택',
    'matcher.sca':         '최소 SCA 점수:',
    'matcher.budget':      '최대 예산:',
    'matcher.next':        '다음',
    'matcher.results':     '결과 보기',
    'matcher.prev':        '← 이전',
    'matcher.vol_sample':  '샘플 (200g 무료)',
    'matcher.vol_micro':   '마이크로 로트 (1–10 포대)',
    'matcher.vol_lot':     '전체 로트 (10–50 포대)',
    'matcher.vol_cont':    '컨테이너 (300+ 포대)',
    'matcher.taste_choc':  '클래식 초콜릿',
    'matcher.taste_cit':   '시트러스 & 밝음',
    'matcher.taste_flor':  '플로럴 & 섬세함',
    'matcher.taste_exo':   '이국적 발효',
    'matcher.taste_swe':   '달콤함 & 꿀',
    'home.hero':       '세계에서 가장 추적 가능한 커피가 여기서 탄생합니다',
    'home.sub':        '우일라 지역 고메 커피의 직접 유통. 실시간 가격, 블록체인 추적성 및 최상급 스페셜티 로트 접근.',
    'home.cta':        '카탈로그 탐색',
    'home.cta2':       '재배자이신가요? 합류하세요',
    'home.feat1_t':    '원산지 인증',
    'home.feat1_d':    '농장에서 로스터리까지 블록체인으로 추적된 각 로트. Polygon의 불변 기록.',
    'home.feat2_t':    '실시간 공정 가격',
    'home.feat2_d':    'NY ICE 시장 데이터 + 지역 차등 + SCA 품질 프리미엄으로 계산된 가격.',
    'home.feat3_t':    '재배자에서 로스터로',
    'home.feat3_d':    '중간 상인 없음. 공정하고 투명한 결제로 우일라 생산자에게서 직접 구매.',
    'home.featured':   '추천 로트',
    'home.now':        '지금 가능',
    'home.see_all':    '전체 카탈로그 보기',
    'home.how':        '어떻게 작동하나요?',
    'home.how_sub':    '5단계로 농장에서 창고까지',
    'home.step1_t':    '등록',
    'home.step1_d':    '국제 구매자로 계정 생성',
    'home.step2_t':    '탐색',
    'home.step2_d':    '고급 필터와 커피 매처로 로트 검색',
    'home.step3_t':    '분석',
    'home.step3_d':    '감각 프로파일, SCA 점수 및 블록체인 추적성 검토',
    'home.step4_t':    '오퍼',
    'home.step4_d':    '원하는 가격과 인코텀으로 공식 오퍼 제출',
    'home.step5_t':    '수령',
    'home.step5_d':    '조율된 물류. 농장에서 로스터리까지',
    'home.stat1':      '활성 재배자',
    'home.stat2':      '구매자 국가',
    'home.stat3':      '최대 SCA 점수',
    'home.stat4':      '농장 추적 가능',
    'home.voices':     '우일라의 목소리',
    'home.voices_sub': '재배자들의 이야기',
    'home.cta_title':  '독점 카탈로그 접근',
    'home.cta_sub':    '국제 구매자로 등록하고 실시간 가격과 완전한 추적성을 갖춘 스페셜티 로트에 접근하세요.',
    'home.reg_name':   '전체 이름',
    'home.reg_co':     '회사',
    'home.reg_email':  '비즈니스 이메일',
    'home.reg_country':'국가',
    'home.reg_btn':    '카탈로그 접근을 원합니다',
    'home.reg_ok_t':   '요청이 전송되었습니다!',
    'home.reg_ok_d':   '24시간 이내에 카탈로그 접근 권한과 함께 연락드리겠습니다.',
    'home.muestra':    '샘플',
    'home.oferta':     '오퍼',
    'footer.rights':   '© 2026 Organicode. 모든 권리 보유.',
    'footer.loc':      '콜롬비아 우일라주 피탈리토',
    'footer.prices':   '실시간 가격',
    'footer.export':   '국제 수출',
  },
};

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const stored = (typeof window !== 'undefined'
    ? (localStorage.getItem('organicode_lang') as Lang || 'en')
    : 'en') as Lang;
  const [lang, setLangState] = useState<Lang>(stored);

  const setLang = (l: Lang) => {
    localStorage.setItem('organicode_lang', l);
    setLangState(l);
  };

  const t = (key: string) => translations[lang][key] ?? translations['en'][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
